# Generated by Django 2.2 on 2019-05-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
