# Generated by Django 2.2 on 2019-05-30 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtaani', '0002_userprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Profile_photo',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
